services:
  karsaz:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    container_name: karsaz
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
        - .:/app
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres
    restart: 'always'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
