src = ["apps", "core", "config"]

target-version = "py311"

line-length = 88

exclude = [
  ".venv",
  "**/migrations/**",
  "__pycache__",
  "static",
  "media"
]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false

[lint]
select = [
  "E",     # PEP8 Errors
  "F",     # Pyflakes
  "I",     # isort
  "B",     # bugbear
  "UP",    # pyupgrade
  "C90",   # mccabe complexity
  "N",     # pep8-naming
  "DJ",    # Django
  "S",     # Bandit
  "RUF"    # Ruff internal
]
ignore = [
  "E501",
  "DJ001",
  "S101",
]

[mccabe]
max-complexity = 10

[lint.isort]
known-first-party = ["apps", "core", "config"]
force-sort-within-sections = true
combine-as-imports = true
