# Generated by Django 5.2.1 on 2025-06-02 16:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("is_remote", models.BooleanField(default=False)),
                ("description", models.TextField()),
                ("url", models.URLField(max_length=1000)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("full_time", "تمام\u200cوقت"),
                            ("part_time", "پاره\u200cوقت"),
                            ("contract", "قراردادی"),
                            ("internship", "کارآموزی"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "seniority_level",
                    models.CharField(
                        choices=[
                            ("junior", "Junior"),
                            ("mid", "Mid"),
                            ("senior", "Senior"),
                            ("lead", "Lead"),
                        ],
                        max_length=50,
                    ),
                ),
                ("salary", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "salary_type",
                    models.CharField(
                        choices=[("fixed", "قیمت ثابت"), ("negotiable", "توافقی")],
                        default="fixed",
                        max_length=20,
                    ),
                ),
                ("source", models.CharField(max_length=100)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "province",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.province",
                    ),
                ),
                ("skills", models.ManyToManyField(blank=True, to="jobs.skill")),
            ],
            options={
                "ordering": ("-posted_at",),
                "indexes": [
                    models.Index(fields=["title"], name="jobs_jobpos_title_afd3ed_idx"),
                    models.Index(
                        fields=["company"], name="jobs_jobpos_company_288798_idx"
                    ),
                    models.Index(
                        fields=["province"], name="jobs_jobpos_provinc_cf402d_idx"
                    ),
                ],
            },
        ),
    ]
