# Generated by Django 5.2.1 on 2025-05-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("is_remote", models.BooleanField(default=False)),
                ("description", models.TextField()),
                ("url", models.URLField(max_length=1000)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("full_time", "تمام\u200cوقت"),
                            ("part_time", "پاره\u200cوقت"),
                            ("contract", "قراردادی"),
                            ("internship", "کارآموزی"),
                            ("freelance", "فریلنس"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "seniority_level",
                    models.CharField(
                        choices=[
                            ("junior", "Junior"),
                            ("mid", "Mid"),
                            ("senior", "Senior"),
                            ("lead", "Lead"),
                        ],
                        max_length=50,
                    ),
                ),
                ("salary", models.CharField(blank=True, max_length=255, null=True)),
                ("source", models.CharField(max_length=100)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("skills", models.ManyToManyField(blank=True, to="jobs.skill")),
            ],
            options={
                "ordering": ("-posted_at",),
                "indexes": [
                    models.Index(fields=["title"], name="jobs_jobpos_title_afd3ed_idx"),
                    models.Index(
                        fields=["company"], name="jobs_jobpos_company_288798_idx"
                    ),
                    models.Index(
                        fields=["location"], name="jobs_jobpos_locatio_73bd90_idx"
                    ),
                ],
            },
        ),
    ]
