# Generated by Django 5.2.1 on 2025-06-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
        ("users", "0003_remove_telegramuser_skills_telegramuser_skills"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobposting",
            name="skills",
        ),
        migrations.AddField(
            model_name="jobposting",
            name="job_url",
            field=models.URLField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jobposting",
            name="military_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="source",
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name="Skill",
        ),
        migrations.AddField(
            model_name="jobposting",
            name="skills",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
