# Generated by Django 5.2.1 on 2025-05-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="salary_type",
            field=models.CharField(
                choices=[("fixed", "قیمت ثابت"), ("negotiable", "توافقی")],
                default="fixed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="salary",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
