# Generated by Django 5.2.1 on 2025-06-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_remove_jobposting_skills_jobposting_job_url_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="jobposting",
            name="jobs_jobpos_company_288798_idx",
        ),
        migrations.RenameField(
            model_name="jobposting",
            old_name="company",
            new_name="company_english",
        ),
        migrations.RemoveField(
            model_name="jobposting",
            name="job_url",
        ),
        migrations.AddField(
            model_name="jobposting",
            name="company_persian",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("full_time", "تمام وقت"),
                    ("part_time", "پاره\u200c وقت"),
                    ("contract", "قراردادی"),
                    ("internship", "کارآموزی"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="seniority_level",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
