# Generated by Django 5.2.1 on 2025-05-31 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("jobs", "0002_jobposting_salary_type_alter_jobposting_salary"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="jobposting",
            name="jobs_jobpos_locatio_73bd90_idx",
        ),
        migrations.RemoveField(
            model_name="jobposting",
            name="location",
        ),
        migrations.AddField(
            model_name="jobposting",
            name="province",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.province",
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("full_time", "تمام\u200cوقت"),
                    ("part_time", "پاره\u200cوقت"),
                    ("contract", "قراردادی"),
                    ("internship", "کارآموزی"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(
                fields=["province"], name="jobs_jobpos_provinc_cf402d_idx"
            ),
        ),
    ]
