# Generated by Django 5.2.1 on 2025-06-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_remove_jobposting_jobs_jobpos_company_288798_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobposting",
            name="military_status",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
