# Generated by Django 5.2.1 on 2025-06-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_alter_jobposting_military_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobposting",
            name="url",
            field=models.URLField(max_length=2083, unique=True),
        ),
    ]
