# Generated by Django 5.2.1 on 2025-06-15 11:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_alter_jobposting_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobposting",
            options={"ordering": ("-created_at",)},
        ),
        migrations.RemoveField(
            model_name="jobposting",
            name="posted_at",
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
