# Generated by Django 5.2.4 on 2025-07-17 23:00

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("jobs", "0006_alter_jobposting_options_remove_jobposting_posted_at_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="jobposting",
            name="jobs_jobpos_title_afd3ed_idx",
        ),
        migrations.RemoveIndex(
            model_name="jobposting",
            name="jobs_jobpos_provinc_cf402d_idx",
        ),
        migrations.AddField(
            model_name="jobposting",
            name="base_salary",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="source",
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"], name="title_trgm_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["description"], name="desc_trgm_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
