# Generated by Django 5.2.1 on 2025-06-02 16:24

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("telegram_id", models.BigIntegerField(unique=True)),
                ("username", models.CharField(blank=True, max_length=150, null=True)),
                ("province", models.JSONField(blank=True, default=list)),
                ("remote_only", models.BooleanField(default=False)),
                ("job_types", models.JSONField(blank=True, default=list)),
                ("seniorities", models.JSONField(blank=True, default=list)),
                ("min_salary", models.PositiveBigIntegerField(blank=True, null=True)),
                ("max_salary", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "salary_type",
                    models.CharField(
                        blank=True,
                        choices=[("fixed", "قیمت ثابت"), ("negotiable", "توافقی")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("skills", models.ManyToManyField(blank=True, to="jobs.skill")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
