# Generated by Django 5.2.1 on 2025-06-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
