# Generated by Django 5.2.1 on 2025-06-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_telegramuser_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telegramuser",
            name="skills",
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="skills",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
