# Generated by Django 5.2.1 on 2025-06-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_telegramuser_skills_telegramuser_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="company",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="military_status",
            field=models.CharField(
                choices=[
                    ("not_important", "مهم نیست"),
                    ("exempt", "معاف دائم"),
                    ("finished", "پایان خدمت"),
                    ("educational_exemption", "معافیت تحصیلی"),
                ],
                default="not_important",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="source",
            field=models.CharField(
                blank=True, choices=[("jobinja", "Jobinja")], max_length=20, null=True
            ),
        ),
    ]
