# Generated by Django 5.2.1 on 2025-05-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_unique_email_case_insensitive_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_client",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_freelancer",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
