# Generated by Django 5.2.1 on 2025-06-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_telegramuser_company_telegramuser_military_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramuser",
            name="military_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("not_important", "مهم نیست"),
                    ("exempt", "معاف دائم"),
                    ("finished", "پایان خدمت"),
                    ("educational_exemption", "معافیت تحصیلی"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
