# Generated by Django 5.2.1 on 2025-05-28 05:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
        ("users", "0005_remove_user_is_admin_remove_user_is_customer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFilterPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("telegram_id", models.BigIntegerField(unique=True)),
                ("username", models.CharField(blank=True, max_length=150, null=True)),
                ("first_name", models.CharField(blank=True, max_length=150, null=True)),
                ("last_name", models.CharField(blank=True, max_length=150, null=True)),
                ("locations", models.JSONField(blank=True, default=list)),
                ("remote_only", models.BooleanField(default=False)),
                ("job_types", models.JSONField(blank=True, default=list)),
                ("seniorities", models.JSONField(blank=True, default=list)),
                ("salary", models.IntegerField(blank=True, null=True)),
                (
                    "salary_type",
                    models.CharField(
                        choices=[("fixed", "قیمت ثابت"), ("negotiable", "توافقی")],
                        default="fixed",
                        max_length=20,
                    ),
                ),
                ("skills", models.ManyToManyField(blank=True, to="jobs.skill")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
