# Generated by Django 5.2.4 on 2025-07-10 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_telegramuser_military_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telegramuser",
            name="company",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="military_status",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="source",
        ),
    ]
