# Generated by Django 5.2.1 on 2025-05-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_userfilterpreference_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfilterpreference",
            name="salary",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
