# Generated by Django 5.2.4 on 2025-07-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_telegramuser_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramuser",
            name="remote_only",
            field=models.BooleanField(default=None),
        ),
    ]
