# Generated by Django 5.2.1 on 2025-05-31 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_userfilterpreference_salary"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userfilterpreference",
            old_name="locations",
            new_name="province",
        ),
    ]
