# Generated by Django 5.2.4 on 2025-07-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_telegramuser_remote_only"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramuser",
            name="remote_only",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
