# Generated by Django 5.2.1 on 2025-06-01 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_remove_jobposting_jobs_jobpos_locatio_73bd90_idx_and_more"),
        ("users", "0008_rename_locations_userfilterpreference_province"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserFilterPreference",
            new_name="TelegramUser",
        ),
    ]
