# Generated by Django 5.2.1 on 2025-06-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_rename_userfilterpreference_telegramuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telegramuser",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="username",
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="title",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
