# Generated by Django 5.2.1 on 2025-06-02 07:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_remove_jobposting_jobs_jobpos_locatio_73bd90_idx_and_more"),
        ("users", "0010_remove_telegramuser_first_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFilterPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("telegram_id", models.BigIntegerField(unique=True)),
                ("username", models.CharField(blank=True, max_length=150, null=True)),
                ("province", models.JSONField(blank=True, default=list)),
                ("remote_only", models.BooleanField(default=False)),
                ("job_types", models.JSONField(blank=True, default=list)),
                ("seniorities", models.JSONField(blank=True, default=list)),
                ("salary", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "salary_type",
                    models.CharField(
                        choices=[("fixed", "قیمت ثابت"), ("negotiable", "توافقی")],
                        default="fixed",
                        max_length=20,
                    ),
                ),
                ("skills", models.ManyToManyField(blank=True, to="jobs.skill")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="TelegramUser",
        ),
    ]
