name: JobFinder

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Build and start containers
        run: make build

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          for i in {1..15}; do
            docker exec postgres pg_isready && echo "PostgreSQL is ready!" && break
            echo "Waiting..."
            sleep 2
          done

      - name: Run tests
        run: make pytest

      - name: Run ruff
        run: make ruff

      - name: Run black check
        run: docker exec django-api black . --check --diff

      - name: Show application logs (on failure only)
        if: failure()
        run: |
          if docker ps -a --format '{{.Names}}' | grep -q '^django-api$'; then
            docker logs django-api
          else
            echo "Container django-api does not exist."
          fi

      - name: Stop containers
        if: always()
        run: make down
